stages:
  - build
  - create
  - run
  - rerun

before_script:
  - docker info

build:
    stage: build
    before_script:
        - docker rmi rust-crosspile:CI || true
    script:
        - docker build -t rust-crosspile:CI .

create:
    stage: create
    before_script:
        - docker rm HELLO-build || true
    script:
        - cd $CI_PROJECT_ID
        - cargo new --bin hello-world
        - cd hello-world
        - docker create -v `pwd`:/home/rust/src --name HELLO-build rust-crosspile:CI

run:
    stage: run
    script:
        - cd $CI_PROJECT_ID
        - cd hello-world
        - docker start -ai HELLO-build
    allow_failure: true

rerun:
    stage: rerun
    script:
        - cd $CI_PROJECT_ID
        - cd hello-world
        - docker start -ai HELLO-build
    allow_failure: true
