stages:
  - build
  - test

before_script:
  - docker info

build:
    stage: build
    script:
        - docker build -t rust-crosspile:CI .

test:
    stage: test
    script:
        - cd $CI_PROJECT_DIR
        - cargo new --bin hello-world
        - cd hello-world
        - docker create -v `pwd`:/home/rust/src --name HELLO-build rust-crosspile:CI
    after_script:
        - docker rm HELLO-build
        - docker rmi rust-crosspile:CI
        - cd $CI_PROJECT_DIR
        - rm -rf hello-world
        - rm -rf rust-crosspile
