cache:
  key: "%CI_COMMIT_REF_SLUG%"
  
stages:
  - build
  - test

before_script:
  - docker info

build:
    stage: build
    script:
        - docker build -t rust-crosspile .

test:
    stage: test
    before_script:
        - cargo new --bin hello-world
        - cd hello-world
        - docker create -v `pwd`:/home/rust/src --name CI_TEST-build rust-crosspile
    script:
        - docker start -ai CI_TEST-build
    after_script:
        - cd ..
        - rm -rf hello-world
        - docker rm CI_TEST-build
