stages:
  - build
  - test


before_script:
  - docker info

build:
    stage: build
    script:
        - docker build -t rust-crosspile .

test:
    stage: test
    before_script:
        - cargo new --bin hello-world
        - cd hello-world
        - docker create -v `pwd`:/home/rust/src --name ne4_konfig-build rust-crosspile
    script:
        - docker start -ai ne4_konfig-build
