stages:
  - build
  - create
  - run
  - rerun

before_script:
  - docker info

build:
    stage: build
    script:
        - docker build -t rust-crosspile:CI .

create:
    stage: create
    before_script:
        - docker rm HELLO-build
        - docker rmi rust-crosspile:CI
    script:
        - cargo new --bin hello-world
        - cd hello-world
        - docker create -v `pwd`:/home/rust/src --name HELLO-build rust-crosspile:CI

run:
    stage: run
    script:
        - cd hello-world
        - docker start -ai HELLO-build
    allow_failure: true

rerun:
    stage: rerun
    script:
        - cd hello-world
        - docker start -ai HELLO-build
    after_script:
        - docker rm HELLO-build
        - docker rmi rust-crosspile:CI
