stages:
  - build
  - create
  - run

before_script:
  - docker info

build:
    stage: build
    before_script:
        - docker rmi rust-crosspile:CI || true
    script:
        - docker build -t rust-crosspile:CI .

create:
    stage: create
    before_script:
        - docker rm HELLO-build || true
        - rm -rf hello-world || true
    script:
        - cargo new --bin hello-world
        - cd hello-world
        - docker create -v `pwd`:/home/rust/src --name HELLO-build rust-crosspile:CI
    cache:
        key: hello-world
        paths:
        - hello-world

run:
    stage: run
    script:
        - chmod 777 hello-world
        - cd hello-world
        - docker start -ai HELLO-build
    cache:
        key: hello-world
        paths:
        - hello-world
    after_script:
        - docker rm HELLO-build
        - docker rmi rust-crosspile:CI
        - rm -rf hello-world
    allow_failure: true
