stages:
  - build
  - create
  - run
  - rerun

before_script:
  - docker info

build:
    stage: build
    before_script:
        - docker rmi rust-crosspile:CI || true
    script:
        - docker build -t rust-crosspile:CI .

create:
    stage: create
    before_script:
        - docker rm HELLO-build || true
        - rm -rf hello-world || true
    script:
        - cargo new --bin hello-world
        - cd hello-world
        - docker create -v `pwd`:/home/rust/src --name HELLO-build rust-crosspile:CI
    cache:
        key: hello-world
        paths:
        - hello-world

run:
    stage: run
    script:
        - ls -lsa .
        - whoami
        - cd hello-world
        - docker start -ai HELLO-build
    cache:
        key: hello-world
        paths:
        - hello-world
    allow_failure: true

rerun:
    stage: rerun
    script:
        - cd hello-world
        - docker start -ai HELLO-build
    cache:
        key: hello-world
        paths:
        - hello-world
    allow_failure: true
